### ISSUE TITLE
Inconsistent assembly names

### ISSUE THREAD

**Issue by joshski** [subsecondtdd/todo-subsecond#7]
@aslakhellesoy on assembly names [in outdated comments](https://github.com/subsecondtdd/todo-subsecond/pull/5):

> If you look at the lego drawing, you'll see that the assemblies are currently named after the `_|⎻|_|⎻|_` legos. I quite like that as a naming convention - it summarises what legos are in the stack.

I'm confused. Why isn't `webdriver-memory` called `webdriver-dom-memory`? and why isn't `webdriver-http-database` called `webdriver-dom-http-database`?

<img width="427" alt="screen shot 2017-11-07 at 17 09 02" src="https://user-images.githubusercontent.com/22017/32507079-65efec8c-c3de-11e7-8afa-b85326d439cc.png">

**Comment by aslakhellesoy** [comment]
I've named the assemblies after the `TodoList` components in the stack exclusively. The in-between components are not part of the naming convention.

It's only the `_|⎻|_|⎻|_` "legos" (with two square studs) that implement the `TodoList` contract/interface (`addTodo({ text })` and `getTodos()`). The other blocks with different shaped studs/tubes on top have a different API.

> Why isn't `webdriver-memory` called `webdriver-dom-memory`?

Because a `WebDriverTodoList` is *always* connected to a DOM, so making that explicit is not necessary. In particular - a `WebDriverTodoList` always has those 3 pink blocks underneath. (Pink is for 3rd party infrastructure, blue is for *our* production code and green is for *our* test code).

**Comment by joshski** [comment]
Right, gotcha!

**Comment by laszbalo** [comment]
Hi,
I am just wondering if the webdriver-memory assembly is named correctly.
The client bundle, which will be loaded by Webdriver, contains BrowserApp which in turn imports HttpTodoList, therefore should it not be called webdriver-http-memory instead?
